brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2024"
enum_discrim_align_threshold = 40
fn_single_line = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
hex_literal_case = "Upper"
indent_style = "Visual"
imports_granularity = "Item"
max_width = 175
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
style_edition = "2024"
unstable_features = true
use_try_shorthand = true
wrap_comments = true